name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install and test
      run: |
        npm install
        NODE_ENV=test npm test
      working-directory: ./dhl_login

    - name: Upload coverage report (HTML)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-html
        path: dhl_login/coverage/lcov-report # HTML coverage report for viewing

    - name: Upload coverage report (LCOV)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-lcov
        path: dhl_login/coverage/lcov.info # LCOV format for external tools

    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: dhl_login/coverage/lcov.info
        delete-old-comments: true

    - name: Check coverage thresholds
      run: |
        echo "Coverage thresholds configured in jest.config.js:"
        echo "- Branches: 40%"
        echo "- Functions: 55%"
        echo "- Lines: 50%"
        echo "- Statements: 50%"
        echo ""
        echo "If tests failed due to coverage, consider:"
        echo "1. Adding more tests to increase coverage"
        echo "2. Adjusting thresholds in jest.config.js if needed"
        echo "3. Excluding files from coverage if appropriate"
      working-directory: ./dhl_login