name: Quality Checks

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  lint-and-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies (dhl_login)
        run: npm ci
        working-directory: ./dhl_login

      - name: Lint (ESLint)
        run: npm run lint
        working-directory: ./dhl_login

      - name: Security audit (fail on high/critical)
        run: |
          npm audit --audit-level=high || (echo "High/Critical vulnerabilities found" >&2; exit 1)
        working-directory: ./dhl_login